# Generated by Django 4.2.5 on 2024-07-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0002_perfilusuario_progresousuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaCuestionario',
            new_name='MateriaCuestionario',
        ),
        migrations.RenameField(
            model_name='textocuestionario',
            old_name='categoria',
            new_name='materia',
        ),
    ]
