# Generated by Django 4.2.5 on 2024-07-25 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorApp', '0005_perfilusuario_progresousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('puntaje', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cuestionarios_completados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='promedio_general',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ProgresoUsuario',
        ),
    ]
