# Generated by Django 4.2.5 on 2024-07-25 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0006_resultadocuestionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_inicial',
            field=models.FloatField(default=1.0),
        ),
    ]
