# Generated by Django 4.2.5 on 2024-07-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0008_remove_perfilusuario_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_inicial',
            field=models.FloatField(default=1.0),
        ),
    ]
