# Generated by Django 4.2.5 on 2024-07-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0009_perfilusuario_nivel_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/user.png', upload_to='fotos_perfil/'),
        ),
    ]
