# Generated by Django 4.2.5 on 2024-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0011_perfilusuario_estado_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
