# Generated by Django 4.2.5 on 2024-07-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0012_perfilusuario_apellido_perfilusuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado_actividad',
        ),
    ]
