# Generated by Django 4.2.5 on 2024-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0013_remove_perfilusuario_estado_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='estado_actividad',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('invisible', 'Invisible'), ('no_molestar', 'No molestar')], default='activo', max_length=20),
        ),
    ]
