# Generated by Django 4.2.5 on 2024-07-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0014_perfilusuario_estado_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado_actividad',
        ),
    ]
