# Generated by Django 4.2.5 on 2024-07-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0016_fotoperfil_remove_perfilusuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto_perfil_actual',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fotos_perfil',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/user.png', upload_to='fotos_perfil/'),
        ),
        migrations.DeleteModel(
            name='FotoPerfil',
        ),
    ]
