# Generated by Django 4.2.5 on 2024-07-27 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0017_remove_perfilusuario_foto_perfil_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_perfil/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actual', to='tutorApp.fotoperfil'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fotos_perfil',
            field=models.ManyToManyField(related_name='usuarios', to='tutorApp.fotoperfil'),
        ),
    ]
